name: Maven Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Maven Verify
    uses: backbase/workflows/.github/workflows/maven-verify.yml@v0.1.0
    secrets:
      maven-username: ${{ secrets.MAVEN_USERNAME }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      github-token: ${{ secrets.GITHUB_TOKEN }}